server:
  port: 8088

spring:
  application:
    name: countrycode
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/countrycode
    username: user
    password: 1234
